use_frameworks!

platform :ios, '9.0'

target 'NXKit_Example' do
  pod 'NXKit', :path => '../'
  pod 'ImageViewer'
end

#https://cloud.tencent.com/developer/article/2105277
#解决Xcode 14 needs selected Development Team for Pod Bundles
post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGN_IDENTITY'] = ''
      end
  end
end
